🎨(#42): Change default body font for Signika
Paris-est-Ludique/ForceOrange pull request #45
Opened 2024-10-16 17:53 UTC by SimonPistache

closes #42 .

2024-10-16 18:13 UTC, SimonPistache commented
Need some testing to see how the font render (size, weight) ...

2024-10-19 11:28 UTC, chatondearu requested changes
You need to add the google font also in the Nuxt layer settings
### here:
https://github.com/Paris-est-Ludique/ForceOrange/blob/737fd5b7deee447c6990cd29b6e4d3c30907cdeb/modules/shared/nuxt.config.ts#L56

2024-10-19 11:28 UTC, chatondearu commented on .vscode/settings.json
I think this changes were automatically generated and are not a voluntary addition. we could remove it ?

2024-10-21 17:19 UTC, SimonPistache commented on .vscode/settings.json
Yes, it's a VScode addon that manage Conventional Commit and help set commits compatible with that formatting.

Let me remove that.

2024-11-01 22:21 UTC, chatondearu approved these changes
LGTM

2024-11-01 22:22 UTC, merged